### ISSUE TITLE
Be able to certify and sign document

### ISSUE THREAD

**Issue by mpiot** [open-pdf-sign/open-pdf-sign#56]
Actually open-pdf-sgin is able to "certify" a document, it should be interesting to be abble to "sign" a document to. Maybe add an option like: --type certify|sign

So when we open a PDF document, in the Signature Panel, we have control on:
 - Signed by...
 - Certified by...

**Comment by cproof** [comment]
Hi @mpoit,

thank you for the issue! 

From what I understand, this basically is possible by not specifying a [permission](https://ec.europa.eu/digital-building-blocks/DSS/webapp-demo/doc/dss-documentation.html). E.g. not specifying results in a document like [signed-signature.pdf](https://github.com/open-pdf-sign/open-pdf-sign/files/12195537/signed-signature.pdf)

It probably makes sense to combine this issue and #47 into a single parameter, allowing either setting no restriction (=signing) or a specific restriction (instead of the current `minimal_changes_permitted`). I'll look into that.

**Comment by mpiot** [comment]
Ooohhh, I've look at the EuDSS documentation to find something about that, but not found 😅

Your idea is really better because it can be interesting to choose between the 3 options 👍

Thanks for your answer

**Comment by cproof** [comment]
Fixed in v0.1.6, using `--certification not-certified` for "signing".
